# Игровое поле
PLATFORM_WIDTH = 30
PLATFORM_HEIGHT = 30
WIN_WIDTH = 1920
WIN_HEIGHT = 1080
BACKGROUND_COLOR = "#FFFFFF"
PLATFORM_COLOR = "#CD5700"
PLATFORM = "-"
SPIKES = "1"
MOBS = "2"
TREASURE = "3"
LASER_RIGHT = "4"
LASER_LEFT = "8"
LEVER = "5"
HERO = "x"
PORTALS = "6"

# Персонаж
SPEED = 5
gg_wight = 25
gg_height = 50
JUMP_POWER = 10
GRAVITY = 0.5

# Шипы
SPIKE_SPEED = 1
SPIKE_DELAY = 1.5

# Лазер
ANIMATION_SLOWNESS = 20
LASER_ANIMATION_SLOWNESS = 10
RAY_SPEED = 40
RAY_WIDTH = 15
RAY_DISTANCE = 17
